[env]
CC = "clang-18"  # for C/C++ deps
CXX = "clang-18" # for C/C++ deps

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "thin"
opt-level = 3
overflow-checks = false
panic = "unwind"
rpath = false
strip = "symbols"
